import random

WORDS_OF_DAY = [
    {"word": "abandon", "translation": "покидать, оставлять", "example": "They had to abandon the sinking ship.", "example_translation": "Им пришлось покинуть тонущий корабль."},
    {"word": "ability", "translation": "способность", "example": "She has the ability to learn fast.", "example_translation": "У неё есть способность быстро учиться."},
    {"word": "able", "translation": "способный", "example": "I am able to swim.", "example_translation": "Я способен плавать."},
    {"word": "about", "translation": "о, около", "example": "Tell me about your trip.", "example_translation": "Расскажи мне о своей поездке."},
    {"word": "above", "translation": "над", "example": "The plane flew above the clouds.", "example_translation": "Самолет летел над облаками."},
    {"word": "abroad", "translation": "за границей", "example": "She dreams of studying abroad.", "example_translation": "Она мечтает учиться за границей."},
    {"word": "absence", "translation": "отсутствие", "example": "His absence was noticed.", "example_translation": "Его отсутствие заметили."},
    {"word": "absolute", "translation": "абсолютный", "example": "That’s absolute nonsense.", "example_translation": "Это абсолютная чепуха."},
    {"word": "absorb", "translation": "поглощать", "example": "Plants absorb sunlight.", "example_translation": "Растения поглощают солнечный свет."},
    {"word": "abstract", "translation": "абстрактный", "example": "Her art is very abstract.", "example_translation": "Ее искусство очень абстрактное."},
    {"word": "abundant", "translation": "обильный", "example": "The garden has an abundant supply of fruit.", "example_translation": "В саду обильный запас фруктов."},
    {"word": "academic", "translation": "академический", "example": "She has strong academic interests.", "example_translation": "У нее сильные академические интересы."},
    {"word": "accelerate", "translation": "ускорять", "example": "The car accelerated quickly.", "example_translation": "Машина быстро ускорилась."},
    {"word": "accept", "translation": "принимать", "example": "I accept your invitation.", "example_translation": "Я принимаю твое приглашение."},
    {"word": "access", "translation": "доступ", "example": "You need a password to access the site.", "example_translation": "Тебе нужен пароль для доступа к сайту."},
    {"word": "accident", "translation": "несчастный случай", "example": "He was injured in a car accident.", "example_translation": "Он пострадал в автомобильной аварии."},
    {"word": "accompany", "translation": "сопровождать", "example": "She will accompany me to the party.", "example_translation": "Она будет сопровождать меня на вечеринку."},
    {"word": "accomplish", "translation": "достигать, выполнять", "example": "We accomplished our goal.", "example_translation": "Мы достигли своей цели."},
    {"word": "account", "translation": "счет, отчет", "example": "I have a bank account.", "example_translation": "У меня есть банковский счет."},
    {"word": "accurate", "translation": "точный", "example": "The data is accurate.", "example_translation": "Данные точные."},
    {"word": "achieve", "translation": "достигать", "example": "She achieved fantastic results.", "example_translation": "Она достигла фантастических результатов."},
    {"word": "acknowledge", "translation": "признавать", "example": "He acknowledged his mistake.", "example_translation": "Он признал свою ошибку."},
    {"word": "acquire", "translation": "приобретать", "example": "She acquired new skills.", "example_translation": "Она приобрела новые навыки."},
    {"word": "adapt", "translation": "адаптироваться", "example": "You need to adapt to the new environment.", "example_translation": "Тебе нужно адаптироваться к новой среде."},
    {"word": "add", "translation": "добавлять", "example": "Add some sugar to the tea.", "example_translation": "Добавь немного сахара в чай."},
    {"word": "address", "translation": "адрес", "example": "Write your address here.", "example_translation": "Напиши свой адрес здесь."},
    {"word": "adequate", "translation": "достаточный", "example": "The supply is adequate.", "example_translation": "Запаса достаточно."},
    {"word": "adjust", "translation": "регулировать, приспосабливать", "example": "Adjust the volume, please.", "example_translation": "Отрегулируй громкость, пожалуйста."},
    {"word": "admire", "translation": "восхищаться", "example": "I admire your courage.", "example_translation": "Я восхищаюсь твоей смелостью."},
    {"word": "admit", "translation": "признавать, допускать", "example": "He admitted he was wrong.", "example_translation": "Он признал, что был неправ."},
    {"word": "adopt", "translation": "принимать, усыновлять", "example": "They decided to adopt a child.", "example_translation": "Они решили усыновить ребенка."},
    {"word": "adult", "translation": "взрослый", "example": "He is an adult now.", "example_translation": "Он теперь взрослый."},
    {"word": "advance", "translation": "продвижение, прогресс", "example": "Technology advances rapidly.", "example_translation": "Технологии быстро развиваются."},
    {"word": "advantage", "translation": "преимущество", "example": "Speaking English is an advantage.", "example_translation": "Знание английского — преимущество."},
    {"word": "adventure", "translation": "приключение", "example": "We went on an exciting adventure.", "example_translation": "Мы отправились в захватывающее приключение."},
    {"word": "advertise", "translation": "рекламировать", "example": "They advertise their product online.", "example_translation": "Они рекламируют свой продукт в интернете."},
    {"word": "advice", "translation": "совет", "example": "Can you give me some advice?", "example_translation": "Можешь дать мне совет?"},
    {"word": "affair", "translation": "дело, роман", "example": "It’s a private affair.", "example_translation": "Это личное дело."},
    {"word": "affect", "translation": "влиять", "example": "The weather affects my mood.", "example_translation": "Погода влияет на мое настроение."},
    {"word": "afford", "translation": "позволить себе", "example": "I can’t afford a new car.", "example_translation": "Я не могу позволить себе новую машину."},
    {"word": "afraid", "translation": "боящийся", "example": "She is afraid of spiders.", "example_translation": "Она боится пауков."},
    {"word": "afternoon", "translation": "день (после полудня)", "example": "I’ll call you in the afternoon.", "example_translation": "Я позвоню тебе после полудня."},
    {"word": "again", "translation": "снова", "example": "Try again.", "example_translation": "Попробуй снова."},
    {"word": "age", "translation": "возраст", "example": "What is your age?", "example_translation": "Какой у тебя возраст?"},
    {"word": "agree", "translation": "соглашаться", "example": "I agree with you.", "example_translation": "Я согласен с тобой."},
    {"word": "ahead", "translation": "впереди", "example": "Go straight ahead.", "example_translation": "Иди прямо."},
    {"word": "aim", "translation": "цель, стремиться", "example": "My aim is to learn English.", "example_translation": "Моя цель — выучить английский."},
    {"word": "air", "translation": "воздух", "example": "The air is fresh here.", "example_translation": "Здесь свежий воздух."},
    {"word": "airplane", "translation": "самолет", "example": "The airplane landed safely.", "example_translation": "Самолет благополучно приземлился."},
    {"word": "alarm", "translation": "будильник, тревога", "example": "Set the alarm for 7 AM.", "example_translation": "Поставь будильник на 7 утра."},
    {"word": "album", "translation": "альбом", "example": "I bought their new album.", "example_translation": "Я купил их новый альбом."},
    {"word": "alive", "translation": "живой", "example": "Is the fish still alive?", "example_translation": "Рыба еще жива?"},
    {"word": "allow", "translation": "позволять", "example": "Allow me to introduce myself.", "example_translation": "Позвольте представиться."},
    {"word": "almost", "translation": "почти", "example": "It’s almost midnight.", "example_translation": "Почти полночь."},
    {"word": "alone", "translation": "один", "example": "She lives alone.", "example_translation": "Она живет одна."},
    {"word": "along", "translation": "вдоль, вместе", "example": "Walk along the river.", "example_translation": "Иди вдоль реки."},
    {"word": "already", "translation": "уже", "example": "I have already eaten.", "example_translation": "Я уже поел."},
    {"word": "also", "translation": "также", "example": "I also like tea.", "example_translation": "Я также люблю чай."},
    {"word": "although", "translation": "хотя", "example": "Although it rained, we went out.", "example_translation": "Хотя шел дождь, мы вышли."},
    {"word": "among", "translation": "среди", "example": "She is popular among colleagues.", "example_translation": "Она популярна среди коллег."},
    {"word": "amount", "translation": "количество", "example": "A large amount of money.", "example_translation": "Большое количество денег."},
    {"word": "amuse", "translation": "развлекать", "example": "The joke amused everyone.", "example_translation": "Шутка развеселила всех."},
    {"word": "ancient", "translation": "древний", "example": "They explored ancient ruins.", "example_translation": "Они исследовали древние руины."},
    {"word": "anger", "translation": "гнев", "example": "He couldn’t hide his anger.", "example_translation": "Он не мог скрыть свой гнев."},
    {"word": "angle", "translation": "угол", "example": "Look at it from a different angle.", "example_translation": "Посмотри на это под другим углом."},
    {"word": "announce", "translation": "объявлять", "example": "They announced the winner.", "example_translation": "Они объявили победителя."},
    {"word": "annual", "translation": "ежегодный", "example": "We have an annual meeting.", "example_translation": "У нас ежегодное собрание."},
    {"word": "anxiety", "translation": "тревога", "example": "She suffers from anxiety.", "example_translation": "Она страдает от тревоги."},
    {"word": "apart", "translation": "врозь", "example": "They live apart.", "example_translation": "Они живут раздельно."},
    {"word": "apologize", "translation": "извиняться", "example": "I apologize for the mistake.", "example_translation": "Я извиняюсь за ошибку."},
    {"word": "apparent", "translation": "очевидный", "example": "It was apparent he was upset.", "example_translation": "Было очевидно, что он расстроен."},
    {"word": "appear", "translation": "появляться, казаться", "example": "A rainbow appeared.", "example_translation": "Появилась радуга."},
    {"word": "appetite", "translation": "аппетит", "example": "I have a good appetite.", "example_translation": "У меня хороший аппетит."},
    {"word": "apply", "translation": "применять, подавать заявку", "example": "Apply the cream gently.", "example_translation": "Нанеси крем аккуратно."},
    {"word": "appreciate", "translation": "ценить", "example": "I appreciate your help.", "example_translation": "Я ценю твою помощь."},
    {"word": "approach", "translation": "подход, приближаться", "example": "We need a new approach.", "example_translation": "Нам нужен новый подход."},
    {"word": "argument", "translation": "спор", "example": "They had a heated argument.", "example_translation": "У них был горячий спор."},
    {"word": "arm", "translation": "рука (от плеча до кисти)", "example": "He broke his arm.", "example_translation": "Он сломал руку."},
    {"word": "arrange", "translation": "организовывать", "example": "Let’s arrange a meeting.", "example_translation": "Давай организуем встречу."},
    {"word": "arrest", "translation": "арестовывать", "example": "The police arrested the thief.", "example_translation": "Полиция арестовала вора."},
    {"word": "arrive", "translation": "прибывать", "example": "The train arrives at 6 p.m.", "example_translation": "Поезд прибывает в 18:00."},
    {"word": "art", "translation": "искусство", "example": "I enjoy modern art.", "example_translation": "Мне нравится современное искусство."},
    {"word": "article", "translation": "статья, предмет", "example": "This article is interesting.", "example_translation": "Эта статья интересная."},
    {"word": "ashamed", "translation": "пристыженный", "example": "He felt ashamed of his behavior.", "example_translation": "Ему было стыдно за свое поведение."},
    {"word": "aspect", "translation": "аспект", "example": "Consider every aspect.", "example_translation": "Рассмотри каждый аспект."},
    {"word": "assist", "translation": "помогать", "example": "Can I assist you?", "example_translation": "Могу я вам помочь?"},
    {"word": "associate", "translation": "ассоциировать, коллега", "example": "I associate summer with holidays.", "example_translation": "Я ассоциирую лето с каникулами."},
    {"word": "assume", "translation": "предполагать", "example": "I assume you are right.", "example_translation": "Я предполагаю, что ты прав."},
    {"word": "atmosphere", "translation": "атмосфера", "example": "The restaurant has a cozy atmosphere.", "example_translation": "В ресторане уютная атмосфера."},
    {"word": "attach", "translation": "прикреплять", "example": "Attach the file to the email.", "example_translation": "Прикрепи файл к письму."},
    {"word": "attempt", "translation": "попытка", "example": "It was a brave attempt.", "example_translation": "Это была смелая попытка."},
    {"word": "attend", "translation": "посещать", "example": "All students attend the lecture.", "example_translation": "Все студенты посещают лекцию."},
    {"word": "attention", "translation": "внимание", "example": "Pay attention to the details.", "example_translation": "Обрати внимание на детали."},
    {"word": "attract", "translation": "привлекать", "example": "The light attracts insects.", "example_translation": "Свет привлекает насекомых."},
    {"word": "audience", "translation": "аудитория, зрители", "example": "The audience applauded loudly.", "example_translation": "Зрители громко аплодировали."},
    {"word": "author", "translation": "автор", "example": "Who is your favorite author?", "example_translation": "Кто твой любимый автор?"},
    {"word": "autumn", "translation": "осень", "example": "I love autumn leaves.", "example_translation": "Я люблю осенние листья."},
    {"word": "available", "translation": "доступный", "example": "The book is available online.", "example_translation": "Книга доступна онлайн."},
    {"word": "average", "translation": "средний", "example": "His average score is high.", "example_translation": "Его средний балл высокий."},
    {"word": "avoid", "translation": "избегать", "example": "Avoid eating late at night.", "example_translation": "Избегай есть поздно ночью."},
    {"word": "awake", "translation": "бодрствующий", "example": "I am still awake.", "example_translation": "Я все еще не сплю."},
    {"word": "award", "translation": "награда", "example": "She won an award.", "example_translation": "Она выиграла награду."},
    {"word": "aware", "translation": "осведомленный", "example": "Are you aware of the problem?", "example_translation": "Ты осведомлен о проблеме?"},
    {"word": "awful", "translation": "ужасный", "example": "The weather is awful today.", "example_translation": "Погода сегодня ужасная."},
    {"word": "awkward", "translation": "неловкий", "example": "It was an awkward silence.", "example_translation": "Это было неловкое молчание."},
    {"word": "back", "translation": "спина, назад", "example": "Stand with your back straight.", "example_translation": "Стой с прямой спиной."},
    {"word": "background", "translation": "фон, происхождение", "example": "She has a background in design.", "example_translation": "У нее образование в области дизайна."},
    {"word": "balance", "translation": "баланс", "example": "Keep your balance.", "example_translation": "Удерживай равновесие."},
    {"word": "ball", "translation": "мяч, бал", "example": "Throw the ball!", "example_translation": "Бросай мяч!"},
    {"word": "ban", "translation": "запрет", "example": "They introduced a ban on smoking.", "example_translation": "Они ввели запрет на курение."},
    {"word": "bank", "translation": "банк, берег", "example": "I need to go to the bank.", "example_translation": "Мне нужно сходить в банк."},
    {"word": "base", "translation": "основа, база", "example": "The story is based on facts.", "example_translation": "История основана на фактах."},
    {"word": "bath", "translation": "ванна", "example": "I take a bath every evening.", "example_translation": "Я принимаю ванну каждый вечер."},
    {"word": "battle", "translation": "битва", "example": "They won the battle.", "example_translation": "Они выиграли битву."},
    {"word": "beach", "translation": "пляж", "example": "Let’s go to the beach.", "example_translation": "Пойдем на пляж."},
    {"word": "bear", "translation": "медведь, выносить", "example": "I can’t bear the pain.", "example_translation": "Я не могу выносить боль."},
    {"word": "beat", "translation": "бить, ритм", "example": "The drummer beat the drum loudly.", "example_translation": "Барабанщик громко бил в барабан."},
    {"word": "beautiful", "translation": "красивый", "example": "What a beautiful view!", "example_translation": "Какой красивый вид!"},
    {"word": "because", "translation": "потому что", "example": "I stayed home because I was sick.", "example_translation": "Я остался дома, потому что болел."},
    {"word": "become", "translation": "становиться", "example": "She wants to become a doctor.", "example_translation": "Она хочет стать врачом."},
    {"word": "beef", "translation": "говядина", "example": "I don’t eat beef.", "example_translation": "Я не ем говядину."},
    {"word": "beg", "translation": "просить, умолять", "example": "He begged for forgiveness.", "example_translation": "Он умолял о прощении."},
    {"word": "begin", "translation": "начинать", "example": "Let’s begin the lesson.", "example_translation": "Давай начнем урок."},
    {"word": "behave", "translation": "вести себя", "example": "Please behave yourself.", "example_translation": "Пожалуйста, веди себя хорошо."},
    {"word": "behind", "translation": "позади", "example": "The garden is behind the house.", "example_translation": "Сад находится позади дома."},
    {"word": "believe", "translation": "верить", "example": "Do you believe in ghosts?", "example_translation": "Ты веришь в привидений?"},
    {"word": "bell", "translation": "колокол, звонок", "example": "The bell rang loudly.", "example_translation": "Колокол прозвенел громко."},
    {"word": "belong", "translation": "принадлежать", "example": "This book belongs to me.", "example_translation": "Эта книга принадлежит мне."},
    {"word": "below", "translation": "ниже, под", "example": "The text below explains it.", "example_translation": "Текст ниже объясняет это."},
    {"word": "belt", "translation": "ремень", "example": "Fasten your seat belt.", "example_translation": "Пристегни ремень безопасности."},
    {"word": "bend", "translation": "сгибать(ся)", "example": "Bend your knees slightly.", "example_translation": "Слегка согни колени."},
    {"word": "benefit", "translation": "выгода, польза", "example": "Exercise has many benefits.", "example_translation": "Упражнения приносят много пользы."},
    {"word": "bet", "translation": "ставка, держать пари", "example": "I bet you can’t do it.", "example_translation": "Спорим, ты не сможешь."},
    {"word": "beyond", "translation": "за пределами", "example": "That’s beyond my understanding.", "example_translation": "Это выше моего понимания."},
    {"word": "bill", "translation": "счет (в ресторане), банкнота", "example": "Can we have the bill, please?", "example_translation": "Можно счет, пожалуйста?"},
    {"word": "bin", "translation": "мусорное ведро", "example": "Throw it in the bin.", "example_translation": "Выбрось это в ведро."},
    {"word": "bit", "translation": "немного, кусочек", "example": "Wait a bit.", "example_translation": "Подожди немного."},
    {"word": "bitter", "translation": "горький", "example": "The coffee was too bitter.", "example_translation": "Кофе был слишком горьким."},
    {"word": "blame", "translation": "винить", "example": "Don’t blame me for the mistake.", "example_translation": "Не вини меня за ошибку."},
    {"word": "blank", "translation": "пустой, чистый лист", "example": "Please fill in the blank.", "example_translation": "Заполните пропуск."},
    {"word": "blind", "translation": "слепой", "example": "He is blind in one eye.", "example_translation": "Он слеп на один глаз."},
    {"word": "block", "translation": "блокировать, квартал", "example": "The road is blocked.", "example_translation": "Дорога перекрыта."},
    {"word": "blood", "translation": "кровь", "example": "Donate blood if you can.", "example_translation": "Сдай кровь, если можешь."},
    {"word": "blow", "translation": "дуть, удар", "example": "The wind blows strongly.", "example_translation": "Ветер сильно дует."},
    {"word": "board", "translation": "доска, совет, борт", "example": "Write on the board.", "example_translation": "Пиши на доске."},
    {"word": "boat", "translation": "лодка", "example": "We rented a boat.", "example_translation": "Мы арендовали лодку."},
    {"word": "boil", "translation": "кипятить", "example": "Boil the water for tea.", "example_translation": "Вскипяти воду для чая."},
    {"word": "bold", "translation": "смелый, жирный (шрифт)", "example": "Make the title bold.", "example_translation": "Сделай заголовок жирным."},
    {"word": "bomb", "translation": "бомба", "example": "The bomb exploded.", "example_translation": "Бомба взорвалась."},
    {"word": "bone", "translation": "кость", "example": "Be careful of fish bones.", "example_translation": "Осторожно с рыбными костями."},
    {"word": "book", "translation": "книга", "example": "I’m reading a good book.", "example_translation": "Я читаю хорошую книгу."},
    {"word": "border", "translation": "граница", "example": "They crossed the border.", "example_translation": "Они пересекли границу."},
    {"word": "borrow", "translation": "занимать (у кого-то)", "example": "Can I borrow your pen?", "example_translation": "Можно одолжить твою ручку?"},
    {"word": "boss", "translation": "начальник", "example": "My boss is very kind.", "example_translation": "Мой начальник очень добрый."},
    {"word": "bother", "translation": "беспокоить", "example": "Don’t bother me now.", "example_translation": "Не беспокой меня сейчас."},
    {"word": "bottle", "translation": "бутылка", "example": "A bottle of water, please.", "example_translation": "Бутылку воды, пожалуйста."},
    {"word": "bottom", "translation": "дно, низ", "example": "Read the bottom line.", "example_translation": "Прочитай нижнюю строку."},
    {"word": "bowl", "translation": "миска, чаша", "example": "I had a bowl of soup.", "example_translation": "Я съел миску супа."},
    {"word": "box", "translation": "коробка", "example": "Open the box carefully.", "example_translation": "Открой коробку осторожно."},
    {"word": "boy", "translation": "мальчик", "example": "The boy is playing outside.", "example_translation": "Мальчик играет на улице."},
    {"word": "brain", "translation": "мозг", "example": "Use your brain!", "example_translation": "Подумай головой!"},
    {"word": "branch", "translation": "ветка, филиал", "example": "A bird sat on a branch.", "example_translation": "Птица сидела на ветке."},
    {"word": "brand", "translation": "бренд", "example": "Which brand do you prefer?", "example_translation": "Какой бренд ты предпочитаешь?"},
    {"word": "brave", "translation": "храбрый", "example": "You are very brave.", "example_translation": "Ты очень храбрый."},
    {"word": "bread", "translation": "хлеб", "example": "I bought fresh bread.", "example_translation": "Я купил свежий хлеб."},
    {"word": "break", "translation": "ломать, перерыв", "example": "Take a break every hour.", "example_translation": "Делай перерыв каждый час."},
    {"word": "breakfast", "translation": "завтрак", "example": "I had eggs for breakfast.", "example_translation": "Я съел яйца на завтрак."},
    {"word": "breath", "translation": "дыхание", "example": "Take a deep breath.", "example_translation": "Сделай глубокий вдох."},
    {"word": "brick", "translation": "кирпич", "example": "The wall is made of bricks.", "example_translation": "Стена сделана из кирпичей."},
    {"word": "bridge", "translation": "мост", "example": "Cross the bridge.", "example_translation": "Перейди мост."},
    {"word": "brief", "translation": "краткий", "example": "Give a brief explanation.", "example_translation": "Дай краткое объяснение."},
    {"word": "bright", "translation": "яркий, умный", "example": "What a bright light!", "example_translation": "Какой яркий свет!"},
    {"word": "brilliant", "translation": "блестящий, гениальный", "example": "That’s a brilliant idea!", "example_translation": "Это блестящая идея!"},
    {"word": "bring", "translation": "приносить", "example": "Bring me the menu, please.", "example_translation": "Принеси мне меню, пожалуйста."},
    {"word": "broad", "translation": "широкий", "example": "He has broad shoulders.", "example_translation": "У него широкие плечи."},
    {"word": "broadcast", "translation": "транслировать", "example": "The match was broadcast live.", "example_translation": "Матч транслировался в прямом эфире."},
    {"word": "brother", "translation": "брат", "example": "My brother is older.", "example_translation": "Мой брат старше."},
    {"word": "brown", "translation": "коричневый", "example": "She has brown eyes.", "example_translation": "У нее карие глаза."},
    {"word": "brush", "translation": "щетка, кисть", "example": "Brush your teeth twice a day.", "example_translation": "Чисти зубы два раза в день."},
    {"word": "budget", "translation": "бюджет", "example": "We need to plan the budget.", "example_translation": "Нам нужно спланировать бюджет."},
    {"word": "build", "translation": "строить", "example": "They plan to build a school.", "example_translation": "Они планируют построить школу."},
    {"word": "bullet", "translation": "пуля", "example": "The bullet missed him.", "example_translation": "Пуля пролетела мимо него."},
    {"word": "bunch", "translation": "связка, куча", "example": "A bunch of flowers.", "example_translation": "Букет цветов."},
    {"word": "burn", "translation": "гореть, жечь", "example": "Don’t burn the toast.", "example_translation": "Не сожги тост."},
    {"word": "burst", "translation": "взрываться, лопаться", "example": "The balloon burst.", "example_translation": "Шарик лопнул."},
    {"word": "bury", "translation": "хоронить, закапывать", "example": "They buried the treasure.", "example_translation": "Они закопали клад."},
    {"word": "bus", "translation": "автобус", "example": "I go to work by bus.", "example_translation": "Я езжу на работу на автобусе."},
    {"word": "bush", "translation": "куст", "example": "A rabbit hid in the bush.", "example_translation": "Кролик спрятался в кустах."},
    {"word": "business", "translation": "бизнес, дело", "example": "Mind your own business.", "example_translation": "Не лезь не в свое дело."},
    {"word": "butter", "translation": "масло сливочное", "example": "Spread butter on the bread.", "example_translation": "Намажь масло на хлеб."},
    {"word": "button", "translation": "пуговица, кнопка", "example": "Press the red button.", "example_translation": "Нажми красную кнопку."},
    {"word": "buy", "translation": "покупать", "example": "Where can I buy tickets?", "example_translation": "Где я могу купить билеты?"},
    {"word": "cabin", "translation": "каюта, хижина", "example": "We stayed in a log cabin.", "example_translation": "Мы остановились в бревенчатой хижине."},
    {"word": "cabinet", "translation": "шкаф, кабинет министров", "example": "Put the files in the cabinet.", "example_translation": "Положи файлы в шкаф."},
    {"word": "cable", "translation": "кабель", "example": "Connect the cable.", "example_translation": "Подключи кабель."},
    {"word": "cake", "translation": "торт, пирожное", "example": "A piece of chocolate cake.", "example_translation": "Кусок шоколадного торта."},
    {"word": "calculate", "translation": "вычислять", "example": "Calculate the total cost.", "example_translation": "Вычисли общую стоимость."},
    {"word": "call", "translation": "звонить, называть", "example": "Call me later.", "example_translation": "Позвони мне позже."},
    {"word": "calm", "translation": "спокойный", "example": "Keep calm and carry on.", "example_translation": "Сохраняй спокойствие и продолжай."},
    {"word": "camera", "translation": "камера, фотоаппарат", "example": "I forgot my camera.", "example_translation": "Я забыл фотоаппарат."},
    {"word": "camp", "translation": "лагерь", "example": "We went to summer camp.", "example_translation": "Мы ездили в летний лагерь."},
    {"word": "cancel", "translation": "отменять", "example": "Cancel the order.", "example_translation": "Отмени заказ."},
    {"word": "candidate", "translation": "кандидат", "example": "He is a strong candidate.", "example_translation": "Он сильный кандидат."},
    {"word": "cap", "translation": "кепка, крышка", "example": "Wear a cap to protect your head.", "example_translation": "Надень кепку, чтобы защитить голову."},
    {"word": "capable", "translation": "способный", "example": "She is capable of doing this.", "example_translation": "Она способна сделать это."},
    {"word": "capital", "translation": "столица, капитал", "example": "London is the capital of the UK.", "example_translation": "Лондон — столица Великобритании."},
    {"word": "capture", "translation": "захватывать, запечатлеть", "example": "The photo captures a beautiful moment.", "example_translation": "Фото запечатлело прекрасный момент."},
    {"word": "car", "translation": "машина", "example": "I drive an electric car.", "example_translation": "Я вожу электрическую машину."},
    {"word": "card", "translation": "карточка", "example": "I paid with a credit card.", "example_translation": "Я заплатил кредитной картой."},
    {"word": "care", "translation": "забота, уход", "example": "Take care of yourself.", "example_translation": "Береги себя."},
    {"word": "career", "translation": "карьера", "example": "She has a successful career.", "example_translation": "У нее успешная карьера."},
    {"word": "carpet", "translation": "ковер", "example": "The carpet is soft.", "example_translation": "Ковер мягкий."},
    {"word": "carry", "translation": "нести", "example": "Can you carry this bag?", "example_translation": "Можешь понести эту сумку?"},
    {"word": "case", "translation": "случай, чемодан, футляр", "example": "In case of fire, use the stairs.", "example_translation": "В случае пожара пользуйтесь лестницей."},
    {"word": "cash", "translation": "наличные", "example": "I paid in cash.", "example_translation": "Я заплатил наличными."},
    {"word": "cast", "translation": "бросать, актерский состав", "example": "The cast of the film is great.", "example_translation": "Актерский состав фильма отличный."},
    {"word": "cat", "translation": "кошка", "example": "My cat loves sleeping.", "example_translation": "Моя кошка любит спать."},
    {"word": "catch", "translation": "ловить", "example": "Catch the ball!", "example_translation": "Лови мяч!"},
    {"word": "category", "translation": "категория", "example": "It belongs to a different category.", "example_translation": "Это относится к другой категории."},
    {"word": "cause", "translation": "причина, вызывать", "example": "The storm caused a blackout.", "example_translation": "Буря вызвала отключение электричества."},
    {"word": "celebrate", "translation": "праздновать", "example": "Let’s celebrate your birthday.", "example_translation": "Давай отпразднуем твой день рождения."},
    {"word": "cell", "translation": "клетка, ячейка, мобильник", "example": "A human body has millions of cells.", "example_translation": "Тело человека состоит из миллионов клеток."},
    {"word": "center", "translation": "центр", "example": "The hotel is in the city center.", "example_translation": "Отель находится в центре города."},
    {"word": "century", "translation": "век", "example": "The 21st century began in 2001.", "example_translation": "21 век начался в 2001 году."},
    {"word": "certain", "translation": "определенный, уверенный", "example": "I’m certain I locked the door.", "example_translation": "Я уверен, что закрыл дверь."},
    {"word": "chain", "translation": "цепь, сеть", "example": "A chain of events.", "example_translation": "Цепь событий."},
    {"word": "chair", "translation": "стул", "example": "Sit on the chair.", "example_translation": "Сядь на стул."},
    {"word": "challenge", "translation": "вызов, сложная задача", "example": "It’s a real challenge.", "example_translation": "Это настоящий вызов."},
    {"word": "champion", "translation": "чемпион", "example": "She became world champion.", "example_translation": "Она стала чемпионкой мира."},
    {"word": "chance", "translation": "шанс", "example": "Give me a chance.", "example_translation": "Дай мне шанс."},
    {"word": "change", "translation": "менять(ся)", "example": "Change is necessary.", "example_translation": "Изменения необходимы."},
    {"word": "channel", "translation": "канал", "example": "Which channel is it on?", "example_translation": "По какому каналу это идет?"},
    {"word": "chapter", "translation": "глава", "example": "Read the first chapter.", "example_translation": "Прочитай первую главу."},
    {"word": "character", "translation": "персонаж, характер", "example": "He has a strong character.", "example_translation": "У него сильный характер."},
    {"word": "charge", "translation": "заряжать, плата, обвинение", "example": "How much do you charge?", "example_translation": "Сколько вы берете?"},
    {"word": "charity", "translation": "благотворительность", "example": "They gave money to charity.", "example_translation": "Они пожертвовали деньги на благотворительность."},
    {"word": "chat", "translation": "болтать, чат", "example": "We had a nice chat.", "example_translation": "Мы мило поболтали."},
    {"word": "cheap", "translation": "дешевый", "example": "The tickets were cheap.", "example_translation": "Билеты были дешевые."},
    {"word": "cheat", "translation": "жульничать", "example": "Don’t cheat on the exam.", "example_translation": "Не жульничай на экзамене."},
    {"word": "check", "translation": "проверять, счет (амер.)", "example": "Check your email.", "example_translation": "Проверь почту."},
    {"word": "cheek", "translation": "щека", "example": "Tears ran down her cheek.", "example_translation": "Слезы текли по ее щеке."},
    {"word": "cheese", "translation": "сыр", "example": "I like cheese sandwiches.", "example_translation": "Мне нравятся бутерброды с сыром."},
    {"word": "chef", "translation": "шеф-повар", "example": "He works as a chef.", "example_translation": "Он работает шеф-поваром."},
    {"word": "chemical", "translation": "химический, химикат", "example": "Chemical reactions can be dangerous.", "example_translation": "Химические реакции могут быть опасны."},
    {"word": "chest", "translation": "грудная клетка, сундук", "example": "He felt pain in his chest.", "example_translation": "Он почувствовал боль в груди."},
    {"word": "chicken", "translation": "курица, цыпленок", "example": "We had chicken for dinner.", "example_translation": "У нас была курица на ужин."},
    {"word": "chief", "translation": "главный, начальник", "example": "He is the chief of police.", "example_translation": "Он начальник полиции."},
    {"word": "child", "translation": "ребенок", "example": "The child is sleeping.", "example_translation": "Ребенок спит."},
    {"word": "chin", "translation": "подбородок", "example": "He rested his chin on his hand.", "example_translation": "Он оперся подбородком на руку."},
    {"word": "chocolate", "translation": "шоколад", "example": "A bar of dark chocolate.", "example_translation": "Плитка темного шоколада."},
    {"word": "choice", "translation": "выбор", "example": "You have a choice.", "example_translation": "У тебя есть выбор."},
    {"word": "choose", "translation": "выбирать", "example": "Choose a number.", "example_translation": "Выбери число."},
    {"word": "church", "translation": "церковь", "example": "They go to church on Sundays.", "example_translation": "Они ходят в церковь по воскресеньям."},
    {"word": "cigarette", "translation": "сигарета", "example": "He quit smoking cigarettes.", "example_translation": "Он бросил курить сигареты."},
    {"word": "circle", "translation": "круг", "example": "Draw a circle.", "example_translation": "Нарисуй круг."},
    {"word": "citizen", "translation": "гражданин", "example": "She is a citizen of Canada.", "example_translation": "Она гражданка Канады."},
    {"word": "city", "translation": "город", "example": "New York is a big city.", "example_translation": "Нью-Йорк — большой город."},
    {"word": "claim", "translation": "утверждать, требование", "example": "He claimed he saw a UFO.", "example_translation": "Он утверждал, что видел НЛО."},
    {"word": "class", "translation": "класс, урок", "example": "English class starts at 10.", "example_translation": "Урок английского начинается в 10."},
    {"word": "clean", "translation": "чистый, убирать", "example": "Keep the room clean.", "example_translation": "Содержи комнату в чистоте."},
    {"word": "clear", "translation": "ясный, чистый", "example": "Is everything clear?", "example_translation": "Все понятно?"},
    {"word": "clever", "translation": "умный, ловкий", "example": "That’s a clever solution.", "example_translation": "Это остроумное решение."},
    {"word": "click", "translation": "щелчок, нажимать", "example": "Click on the link.", "example_translation": "Нажми на ссылку."},
    {"word": "climate", "translation": "климат", "example": "The climate is changing.", "example_translation": "Климат меняется."},
    {"word": "climb", "translation": "взбираться", "example": "He wants to climb Everest.", "example_translation": "Он хочет взобраться на Эверест."},
    {"word": "clock", "translation": "часы (настенные)", "example": "Look at the clock!", "example_translation": "Посмотри на часы!"},
    {"word": "close", "translation": "закрывать, близкий", "example": "Close the window, please.", "example_translation": "Закрой окно, пожалуйста."},
    {"word": "cloth", "translation": "ткань, тряпка", "example": "Wipe with a cloth.", "example_translation": "Протри тряпкой."},
    {"word": "cloud", "translation": "облако", "example": "There isn’t a cloud in the sky.", "example_translation": "На небе ни облачка."},
    {"word": "club", "translation": "клуб, дубинка", "example": "Join our book club.", "example_translation": "Вступай в наш книжный клуб."},
    {"word": "coach", "translation": "тренер, автобус", "example": "The coach gave great advice.", "example_translation": "Тренер дал отличный совет."},
    {"word": "coal", "translation": "уголь", "example": "They used to mine coal.", "example_translation": "Раньше здесь добывали уголь."},
    {"word": "coast", "translation": "побережье", "example": "They live near the coast.", "example_translation": "Они живут у побережья."},
    {"word": "coat", "translation": "пальто, слой", "example": "Put on your coat, it’s cold.", "example_translation": "Надень пальто, холодно."},
    {"word": "code", "translation": "код", "example": "Enter your access code.", "example_translation": "Введи свой код доступа."},
    {"word": "coffee", "translation": "кофе", "example": "I need a cup of coffee.", "example_translation": "Мне нужна чашка кофе."},
    {"word": "coin", "translation": "монета", "example": "Do you have a coin?", "example_translation": "У тебя есть монета?"},
    {"word": "cold", "translation": "холодный, простуда", "example": "I caught a cold.", "example_translation": "Я простудился."},
    {"word": "collar", "translation": "воротник", "example": "He grabbed me by the collar.", "example_translation": "Он схватил меня за воротник."},
    {"word": "collect", "translation": "собирать, коллекционировать", "example": "She collects stamps.", "example_translation": "Она коллекционирует марки."},
    {"word": "college", "translation": "колледж", "example": "He attends college.", "example_translation": "Он учится в колледже."},
    {"word": "colour", "translation": "цвет", "example": "What’s your favourite colour?", "example_translation": "Какой твой любимый цвет?"},
    {"word": "column", "translation": "колонна, столбец", "example": "Write your name in the left column.", "example_translation": "Напиши имя в левом столбце."},
    {"word": "combine", "translation": "сочетать, объединять", "example": "Combine all ingredients.", "example_translation": "Смешай все ингредиенты."},
    {"word": "comfort", "translation": "комфорт, утешение", "example": "He found comfort in music.", "example_translation": "Он нашел утешение в музыке."},
    {"word": "command", "translation": "команда, приказ", "example": "The captain gave a command.", "example_translation": "Капитан отдал приказ."},
    {"word": "comment", "translation": "комментарий", "example": "Leave a comment below.", "example_translation": "Оставь комментарий ниже."},
    {"word": "commit", "translation": "совершать, брать обязательства", "example": "Commit to your goals.", "example_translation": "Бери на себя обязательства по целям."},
    {"word": "committee", "translation": "комитет", "example": "The committee meets weekly.", "example_translation": "Комитет собирается еженедельно."},
    {"word": "common", "translation": "общий, распространенный", "example": "It’s a common mistake.", "example_translation": "Это распространенная ошибка."},
    {"word": "communicate", "translation": "общаться", "example": "We communicate by email.", "example_translation": "Мы общаемся по электронной почте."},
    {"word": "community", "translation": "сообщество", "example": "The community supports the project.", "example_translation": "Сообщество поддерживает проект."},
    {"word": "company", "translation": "компания", "example": "I work for a tech company.", "example_translation": "Я работаю в технологической компании."},
    {"word": "compare", "translation": "сравнивать", "example": "Compare prices before buying.", "example_translation": "Сравни цены перед покупкой."},
    {"word": "compete", "translation": "соревноваться", "example": "Athletes compete for medals.", "example_translation": "Спортсмены соревнуются за медали."},
    {"word": "complain", "translation": "жаловаться", "example": "He complained about the noise.", "example_translation": "Он пожаловался на шум."},
    {"word": "complete", "translation": "завершать, полный", "example": "Complete the form.", "example_translation": "Заполни форму."},
    {"word": "complex", "translation": "сложный", "example": "It’s a complex problem.", "example_translation": "Это сложная проблема."},
    {"word": "computer", "translation": "компьютер", "example": "I use a computer every day.", "example_translation": "Я пользуюсь компьютером каждый день."},
    {"word": "concentrate", "translation": "концентрироваться", "example": "Concentrate on your work.", "example_translation": "Сосредоточься на работе."},
    {"word": "concept", "translation": "концепция, понятие", "example": "It’s a difficult concept.", "example_translation": "Это сложная концепция."},
    {"word": "concern", "translation": "касаться, беспокойство", "example": "That doesn’t concern you.", "example_translation": "Это тебя не касается."},
    {"word": "conclude", "translation": "заключать, делать вывод", "example": "We concluded the meeting.", "example_translation": "Мы завершили встречу."},
    {"word": "condition", "translation": "состояние, условие", "example": "The car is in good condition.", "example_translation": "Машина в хорошем состоянии."},
    {"word": "conduct", "translation": "проводить, поведение", "example": "They conducted an experiment.", "example_translation": "Они провели эксперимент."},
    {"word": "conference", "translation": "конференция", "example": "She spoke at the conference.", "example_translation": "Она выступала на конференции."},
    {"word": "confidence", "translation": "уверенность", "example": "He lacks confidence.", "example_translation": "Ему не хватает уверенности."},
    {"word": "confirm", "translation": "подтверждать", "example": "Please confirm your email.", "example_translation": "Пожалуйста, подтвердите свою почту."},
    {"word": "conflict", "translation": "конфликт, противоречие", "example": "Avoid conflict at work.", "example_translation": "Избегай конфликтов на работе."},
    {"word": "confuse", "translation": "путать", "example": "I often confuse these two words.", "example_translation": "Я часто путаю эти два слова."},
    {"word": "connect", "translation": "соединять(ся)", "example": "Connect the printer to the computer.", "example_translation": "Подключи принтер к компьютеру."},
    {"word": "conscious", "translation": "сознательный, в сознании", "example": "She is still conscious.", "example_translation": "Она все еще в сознании."},
    {"word": "consequence", "translation": "последствие", "example": "Think of the consequences.", "example_translation": "Подумай о последствиях."},
    {"word": "consider", "translation": "рассматривать, считать", "example": "Consider all options.", "example_translation": "Рассмотри все варианты."},
    {"word": "constant", "translation": "постоянный", "example": "There was constant noise.", "example_translation": "Был постоянный шум."},
    {"word": "construct", "translation": "строить, конструировать", "example": "They constructed a new bridge.", "example_translation": "Они построили новый мост."},
    {"word": "contact", "translation": "контакт, связываться", "example": "Contact me later.", "example_translation": "Свяжись со мной позже."},
    {"word": "contain", "translation": "содержать", "example": "This box contains books.", "example_translation": "Эта коробка содержит книги."},
    {"word": "content", "translation": "содержание, довольный", "example": "The content of the article is good.", "example_translation": "Содержание статьи хорошее."},
    {"word": "contest", "translation": "соревнование, конкурс", "example": "She won the singing contest.", "example_translation": "Она выиграла конкурс пения."},
    {"word": "continue", "translation": "продолжать", "example": "Continue straight ahead.", "example_translation": "Продолжай идти прямо."},
    {"word": "contract", "translation": "контракт, сокращаться", "example": "Read the contract carefully.", "example_translation": "Внимательно прочитай контракт."},
    {"word": "contrast", "translation": "контраст", "example": "There is a big contrast between them.", "example_translation": "Между ними большой контраст."},
    {"word": "contribute", "translation": "вносить вклад", "example": "Everyone contributed ideas.", "example_translation": "Каждый внес идеи."},
    {"word": "control", "translation": "контроль, управление", "example": "Take control of the situation.", "example_translation": "Возьми ситуацию под контроль."},
    {"word": "convenient", "translation": "удобный", "example": "Is 3 p.m. convenient for you?", "example_translation": "Тебе удобно в 15:00?"},
    {"word": "conversation", "translation": "разговор, беседа", "example": "We had a nice conversation.", "example_translation": "У нас был приятный разговор."},
    {"word": "convince", "translation": "убеждать", "example": "He convinced me to go.", "example_translation": "Он убедил меня пойти."},
    {"word": "cook", "translation": "готовить еду", "example": "I can cook pasta.", "example_translation": "Я умею готовить пасту."},
    {"word": "cool", "translation": "прохладный, крутой", "example": "That’s a cool jacket.", "example_translation": "Классная куртка."},
    {"word": "cooperate", "translation": "сотрудничать", "example": "We need to cooperate.", "example_translation": "Нам нужно сотрудничать."},
    {"word": "copy", "translation": "копия, копировать", "example": "Make a copy of the file.", "example_translation": "Сделай копию файла."},
    {"word": "corner", "translation": "угол", "example": "The shop is on the corner.", "example_translation": "Магазин на углу."},
    {"word": "correct", "translation": "правильный, исправлять", "example": "Is my answer correct?", "example_translation": "Мой ответ правильный?"},
    {"word": "cost", "translation": "стоить, стоимость", "example": "How much does it cost?", "example_translation": "Сколько это стоит?"},
    {"word": "cotton", "translation": "хлопок", "example": "This shirt is 100% cotton.", "example_translation": "Эта рубашка из 100% хлопка."},
    {"word": "cough", "translation": "кашель, кашлять", "example": "I have a bad cough.", "example_translation": "У меня сильный кашель."},
    {"word": "council", "translation": "совет (орган)", "example": "The city council approved the plan.", "example_translation": "Городской совет утвердил план."},
    {"word": "count", "translation": "считать, граф", "example": "Count to ten.", "example_translation": "Сосчитай до десяти."},
    {"word": "country", "translation": "страна, сельская местность", "example": "Which country are you from?", "example_translation": "Из какой ты страны?"},
    {"word": "couple", "translation": "пара", "example": "A couple of days ago.", "example_translation": "Пару дней назад."},
    {"word": "courage", "translation": "мужество, смелость", "example": "It takes courage to speak up.", "example_translation": "Нужна смелость, чтобы высказаться."},
    {"word": "course", "translation": "курс, блюдо, ход", "example": "I’m taking a language course.", "example_translation": "Я прохожу языковой курс."},
    {"word": "court", "translation": "суд, корт", "example": "The case went to court.", "example_translation": "Дело дошло до суда."},
    {"word": "cover", "translation": "покрывать, обложка", "example": "Cover the pot with a lid.", "example_translation": "Накрой кастрюлю крышкой."},
    {"word": "crash", "translation": "авария, грохот", "example": "He survived the plane crash.", "example_translation": "Он выжил в авиакатастрофе."},
    {"word": "create", "translation": "создавать", "example": "She likes to create art.", "example_translation": "Ей нравится создавать искусство."},
    {"word": "credit", "translation": "кредит, доверие", "example": "Give credit where it’s due.", "example_translation": "Воздай должное."},
    {"word": "crime", "translation": "преступление", "example": "The crime rate is low here.", "example_translation": "Уровень преступности здесь низкий."},
    {"word": "criminal", "translation": "преступник, уголовный", "example": "He has a criminal record.", "example_translation": "У него судимость."},
    {"word": "crisis", "translation": "кризис", "example": "We are in a crisis.", "example_translation": "Мы в кризисе."},
    {"word": "criticize", "translation": "критиковать", "example": "Stop criticizing me!", "example_translation": "Перестань меня критиковать!"},
    {"word": "crop", "translation": "урожай, сельхозкультура", "example": "The farmers harvested the crop.", "example_translation": "Фермеры собрали урожай."},
    {"word": "cross", "translation": "пересекать, крест", "example": "Cross the road carefully.", "example_translation": "Переходи дорогу осторожно."},
    {"word": "crowd", "translation": "толпа", "example": "The crowd cheered loudly.", "example_translation": "Толпа громко приветствовала."},
    {"word": "cry", "translation": "плакать, кричать", "example": "Don’t cry, it’s okay.", "example_translation": "Не плачь, все хорошо."},
    {"word": "culture", "translation": "культура", "example": "I love Japanese culture.", "example_translation": "Я люблю японскую культуру."},
    {"word": "cup", "translation": "чашка, кубок", "example": "Would you like a cup of tea?", "example_translation": "Хочешь чашку чая?"},
    {"word": "cure", "translation": "лечить, лекарство", "example": "They found a cure for the disease.", "example_translation": "Они нашли лекарство от болезни."},
    {"word": "curious", "translation": "любопытный", "example": "I’m curious about the results.", "example_translation": "Мне любопытно узнать результаты."},
    {"word": "current", "translation": "текущий, течение", "example": "What is your current job?", "example_translation": "Какая у тебя сейчас работа?"},
    {"word": "curtain", "translation": "занавеска, штора", "example": "Open the curtains, please.", "example_translation": "Открой шторы, пожалуйста."},
    {"word": "curve", "translation": "изгиб, кривая", "example": "The road has a sharp curve.", "example_translation": "У дороги крутой поворот."},
    {"word": "customer", "translation": "клиент, покупатель", "example": "The customer is always right.", "example_translation": "Клиент всегда прав."},
    {"word": "cut", "translation": "резать, порез", "example": "I cut my finger.", "example_translation": "Я порезал палец."},
    {"word": "cycle", "translation": "цикл, велосипед", "example": "Riding a cycle is healthy.", "example_translation": "Езда на велосипеде полезна."},
    {"word": "dad", "translation": "папа", "example": "My dad bought me a gift.", "example_translation": "Папа купил мне подарок."},
    {"word": "daily", "translation": "ежедневный", "example": "I read the daily news.", "example_translation": "Я читаю ежедневные новости."},
    {"word": "damage", "translation": "повреждение, ущерб", "example": "The storm caused damage.", "example_translation": "Буря нанесла ущерб."},
    {"word": "dance", "translation": "танец, танцевать", "example": "Let’s dance!", "example_translation": "Давай потанцуем!"},
    {"word": "danger", "translation": "опасность", "example": "There is a danger of flooding.", "example_translation": "Есть опасность наводнения."},
    {"word": "dark", "translation": "темный", "example": "It gets dark early in winter.", "example_translation": "Зимой рано темнеет."},
    {"word": "data", "translation": "данные", "example": "The data shows an increase.", "example_translation": "Данные показывают рост."},
    {"word": "database", "translation": "база данных", "example": "Store information in a database.", "example_translation": "Храни информацию в базе данных."},
    {"word": "daughter", "translation": "дочь", "example": "My daughter loves to read.", "example_translation": "Моя дочь любит читать."},
    {"word": "dawn", "translation": "рассвет", "example": "We woke up at dawn.", "example_translation": "Мы проснулись на рассвете."},
    {"word": "dead", "translation": "мертвый", "example": "The battery is dead.", "example_translation": "Батарея разряжена (мертва)."},
    {"word": "deal", "translation": "сделка, иметь дело", "example": "We made a deal.", "example_translation": "Мы заключили сделку."},
    {"word": "dear", "translation": "дорогой (в обращении)", "example": "Dear friend, how are you?", "example_translation": "Дорогой друг, как ты?"},
    {"word": "debate", "translation": "дебаты, обсуждать", "example": "They had a lively debate.", "example_translation": "У них была оживленная дискуссия."},
    {"word": "debt", "translation": "долг", "example": "He is in debt.", "example_translation": "Он в долгах."},
    {"word": "decade", "translation": "десятилетие", "example": "The building is over a decade old.", "example_translation": "Этому зданию больше десяти лет."},
    {"word": "decide", "translation": "решать", "example": "You need to decide quickly.", "example_translation": "Тебе нужно решить быстро."},
    {"word": "decision", "translation": "решение", "example": "It was a difficult decision.", "example_translation": "Это было трудное решение."},
    {"word": "declare", "translation": "объявлять, декларировать", "example": "Declare your income.", "example_translation": "Задекларируй свой доход."},
    {"word": "decorate", "translation": "украшать", "example": "We decorated the room.", "example_translation": "Мы украсили комнату."},
    {"word": "deep", "translation": "глубокий", "example": "The water is very deep.", "example_translation": "Вода очень глубокая."},
    {"word": "defend", "translation": "защищать", "example": "He defended his position.", "example_translation": "Он защищал свою позицию."},
    {"word": "define", "translation": "определять", "example": "Define the problem first.", "example_translation": "Сначала определи проблему."},
    {"word": "degree", "translation": "степень, градус", "example": "Water boils at 100 degrees.", "example_translation": "Вода закипает при 100 градусах."},
    {"word": "delay", "translation": "задержка, задерживать", "example": "The flight was delayed.", "example_translation": "Рейс задержали."},
    {"word": "deliver", "translation": "доставлять", "example": "They deliver pizza.", "example_translation": "Они доставляют пиццу."},
    {"word": "demand", "translation": "требовать, спрос", "example": "The product is in high demand.", "example_translation": "Продукт пользуется высоким спросом."},
    {"word": "democracy", "translation": "демократия", "example": "Democracy means free elections.", "example_translation": "Демократия означает свободные выборы."},
    {"word": "department", "translation": "отдел", "example": "She works in the marketing department.", "example_translation": "Она работает в отделе маркетинга."},
    {"word": "depend", "translation": "зависеть", "example": "It depends on the weather.", "example_translation": "Это зависит от погоды."},
    {"word": "describe", "translation": "описывать", "example": "Describe your ideal day.", "example_translation": "Опиши свой идеальный день."},
    {"word": "desert", "translation": "пустыня", "example": "The Sahara is a huge desert.", "example_translation": "Сахара — огромная пустыня."},
    {"word": "deserve", "translation": "заслуживать", "example": "You deserve a break.", "example_translation": "Ты заслужил перерыв."},
    {"word": "design", "translation": "дизайн, разрабатывать", "example": "She designs websites.", "example_translation": "Она разрабатывает веб-сайты."},
    {"word": "desire", "translation": "желание", "example": "He has a desire to travel.", "example_translation": "У него есть желание путешествовать."},
    {"word": "desk", "translation": "письменный стол", "example": "She is sitting at her desk.", "example_translation": "Она сидит за столом."},
    {"word": "destroy", "translation": "разрушать", "example": "The earthquake destroyed the city.", "example_translation": "Землетрясение разрушило город."},
    {"word": "detail", "translation": "деталь, подробность", "example": "Tell me every detail.", "example_translation": "Расскажи мне каждую деталь."},
    {"word": "determine", "translation": "определять, решать", "example": "We need to determine the cause.", "example_translation": "Нам нужно определить причину."},
    {"word": "develop", "translation": "развивать(ся)", "example": "They plan to develop the area.", "example_translation": "Они планируют развивать район."},
    {"word": "device", "translation": "устройство", "example": "Turn off your electronic devices.", "example_translation": "Выключите электронные устройства."},
    {"word": "dialog", "translation": "диалог", "example": "The film has great dialogue.", "example_translation": "В фильме отличные диалоги."},
    {"word": "diary", "translation": "дневник", "example": "She writes in her diary every night.", "example_translation": "Она пишет в дневнике каждый вечер."},
    {"word": "dictate", "translation": "диктовать", "example": "The teacher dictated a sentence.", "example_translation": "Учитель продиктовал предложение."},
    {"word": "die", "translation": "умирать", "example": "The flowers died due to frost.", "example_translation": "Цветы погибли из-за мороза."},
    {"word": "differ", "translation": "отличаться", "example": "Opinions differ on this issue.", "example_translation": "Мнения различаются по этому вопросу."},
    {"word": "dig", "translation": "копать", "example": "They dug a deep hole.", "example_translation": "Они выкопали глубокую яму."},
    {"word": "digital", "translation": "цифровой", "example": "I have a digital camera.", "example_translation": "У меня цифровая камера."},
    {"word": "dinner", "translation": "ужин", "example": "What’s for dinner?", "example_translation": "Что на ужин?"},
    {"word": "direct", "translation": "прямой, направлять", "example": "Can you direct me to the station?", "example_translation": "Можете направить меня на вокзал?"},
    {"word": "disappear", "translation": "исчезать", "example": "The magician made the rabbit disappear.", "example_translation": "Фокусник заставил кролика исчезнуть."},
    {"word": "discover", "translation": "обнаруживать", "example": "They discovered a new planet.", "example_translation": "Они открыли новую планету."},
    {"word": "discuss", "translation": "обсуждать", "example": "Let’s discuss the plan.", "example_translation": "Давайте обсудим план."},
    {"word": "disease", "translation": "болезнь", "example": "Heart disease is common.", "example_translation": "Болезни сердца распространены."},
    {"word": "display", "translation": "показывать, дисплей", "example": "The screen displays the time.", "example_translation": "Экран показывает время."},
    {"word": "distance", "translation": "расстояние", "example": "Keep a safe distance.", "example_translation": "Держите безопасную дистанцию."},
    {"word": "distribute", "translation": "распространять, распределять", "example": "Distribute the leaflets.", "example_translation": "Раздайте листовки."},
    {"word": "district", "translation": "район", "example": "This district is very quiet.", "example_translation": "Этот район очень тихий."},
    {"word": "diverse", "translation": "разнообразный", "example": "Our team is very diverse.", "example_translation": "Наша команда очень разнообразна."},
    {"word": "divide", "translation": "делить", "example": "Divide the cake equally.", "example_translation": "Раздели торт поровну."},
    {"word": "divorce", "translation": "развод", "example": "They got a divorce.", "example_translation": "Они развелись."},
    {"word": "document", "translation": "документ", "example": "Sign the document, please.", "example_translation": "Подпишите документ, пожалуйста."},
    {"word": "dog", "translation": "собака", "example": "I walk my dog twice a day.", "example_translation": "Я выгуливаю собаку дважды в день."},
    {"word": "donate", "translation": "жертвовать", "example": "Donate to charity.", "example_translation": "Пожертвуйте на благотворительность."},
    {"word": "door", "translation": "дверь", "example": "Close the door quietly.", "example_translation": "Закрой дверь тихо."},
    {"word": "double", "translation": "двойной", "example": "Double the amount of sugar.", "example_translation": "Удвой количество сахара."},
    {"word": "doubt", "translation": "сомневаться", "example": "I doubt his story.", "example_translation": "Я сомневаюсь в его истории."},
    {"word": "down", "translation": "вниз, внизу", "example": "Sit down, please.", "example_translation": "Сядь, пожалуйста."},
    {"word": "download", "translation": "скачивать", "example": "Download the file now.", "example_translation": "Скачай файл сейчас."},
    {"word": "draft", "translation": "черновик, сквозняк", "example": "Write a draft first.", "example_translation": "Сначала напиши черновик."},
    {"word": "drag", "translation": "тащить", "example": "Drag the box over here.", "example_translation": "Перетащи коробку сюда."},
    {"word": "drama", "translation": "драма", "example": "She studies drama at school.", "example_translation": "Она изучает драму в школе."},
    {"word": "draw", "translation": "рисовать, тянуть", "example": "I like to draw portraits.", "example_translation": "Мне нравится рисовать портреты."},
    {"word": "dream", "translation": "мечта, сон", "example": "I had a weird dream.", "example_translation": "Мне приснился странный сон."},
    {"word": "dress", "translation": "платье, одеваться", "example": "She wore a red dress.", "example_translation": "Она надела красное платье."},
    {"word": "drink", "translation": "пить, напиток", "example": "Drink plenty of water.", "example_translation": "Пей много воды."},
    {"word": "drive", "translation": "водить машину", "example": "Can you drive a truck?", "example_translation": "Ты умеешь водить грузовик?"},
    {"word": "drop", "translation": "ронять, падение", "example": "Don’t drop the glass!", "example_translation": "Не урони стакан!"},
    {"word": "dry", "translation": "сухой, сушить", "example": "My throat is dry.", "example_translation": "У меня сухо в горле."},
    {"word": "duck", "translation": "утка", "example": "We fed the ducks in the park.", "example_translation": "Мы кормили уток в парке."},
    {"word": "due", "translation": "должный, ожидаемый", "example": "The report is due on Friday.", "example_translation": "Отчет должен быть готов к пятнице."},
    {"word": "dull", "translation": "скучный, тусклый", "example": "The lecture was dull.", "example_translation": "Лекция была скучной."},
    {"word": "dust", "translation": "пыль", "example": "Wipe the dust off the shelf.", "example_translation": "Сотри пыль с полки."},
    {"word": "duty", "translation": "обязанность, долг", "example": "It’s my duty to help you.", "example_translation": "Моя обязанность — помочь тебе."},
]
# (всего 365 слов, полный список — прямо здесь)

NOVICE_TEMPLATES = [
    {
        "question": "Как переводится слово **{word}**?",
        "options": ["{translation}", "{fake1}", "{fake2}"],
        "correct": 0
    },
    {
        "question": "Заполните пропуск: I want to ___ you something important.",
        "options": ["{word}", "{random_eng1}", "{random_eng2}"],   # ← теперь английские фейки
        "correct": 0
    },
    {
        "question": "Выберите правильный перевод:\n\"{example}\"",
        "options": ["{example_translation}", "{fake1}", "{fake2}"],  # ← естественные русские дистракторы
        "correct": 0
    }
]
MIDDLE_TEMPLATES = [
    {"question": "Синоним слова **{word}** это...", "options": ["{synonym}", "{antonym}", "{random_word}"], "correct": 0},
    {"question": "Выберите грамматически верное предложение:", "options": ["He {word_gerund} every day.", "He {word}s every day.", "He {word}ed yesterday."], "correct": 1},
    {"question": "Переведите предложение: \"{example}\"", "options": ["{example_translation}", "{fake_trans1}", "{fake_trans2}"], "correct": 0},
]
PRO_TEMPLATES = [
    {"question": "Идиома со словом **{word}**:", "options": ["{idiom}", "{fake_idiom1}", "{fake_idiom2}"], "correct": 0},
    {"question": "Какое слово лучше всего подходит?\n\"{complex_sentence}\"", "options": ["{word}", "{distractor1}", "{distractor2}"], "correct": 0},
    {"question": "Перефразируйте: \"{example}\"", "options": ["{paraphrase}", "{bad_paraphrase}", "{wrong_meaning}"], "correct": 0},
]

# Вспомогательные данные для генерации (расширяются по необходимости)
SYNONYMS = {"abandon": "leave", "ability": "skill", "able": "capable", "about": "approximately", "above": "over", "abroad": "overseas", "absence": "lack", "absolute": "total", "absorb": "soak up", "abstract": "theoretical"}
ANTONYMS = {"abandon": "keep", "ability": "inability", "able": "unable", "about": "exactly", "above": "below", "abroad": "local"}

# Перемешиваем слова с фиксированным seed, чтобы порядок изменился, но оставался детерминированным
_shuffler = random.Random(42)
_shuffler.shuffle(WORDS_OF_DAY)

def get_daily_word(day_index: int) -> dict:
    return WORDS_OF_DAY[day_index % len(WORDS_OF_DAY)]

def generate_tasks(day_index: int, level: str):
    word_data = get_daily_word(day_index)
    w = word_data["word"]
    trans = word_data["translation"]
    ex = word_data["example"]
    ex_trans = word_data["example_translation"]

    random.seed(f"{day_index}_{level}")

    eng_words_pool = [wd["word"] for wd in WORDS_OF_DAY if wd["word"] != w]
    pool_trans = [wd["translation"] for wd in WORDS_OF_DAY if wd["translation"] != trans]

    if len(pool_trans) >= 2:
        fake1, fake2 = random.sample(pool_trans, 2)
    else:
        fake1, fake2 = "перевод1", "перевод2"

    if len(eng_words_pool) >= 2:
        random_eng1, random_eng2 = random.sample(eng_words_pool, 2)
    else:
        random_eng1, random_eng2 = "word1", "word2"

    tasks = []
    if level == "novice":
        for t in NOVICE_TEMPLATES:
            q = t["question"].format(
                word=w, translation=trans,
                example=ex, example_translation=ex_trans,
                fake1=fake1, fake2=fake2,
                random_eng1=random_eng1, random_eng2=random_eng2
            )
            opts = [opt.format(
                word=w, translation=trans,
                example=ex, example_translation=ex_trans,
                fake1=fake1, fake2=fake2,
                random_eng1=random_eng1, random_eng2=random_eng2
            ) for opt in t["options"]]
            tasks.append({
                "question": q,
                "options": opts,
                "correct": t["correct"],
                "word": w
            })
    elif level == "middle":
        syn = SYNONYMS.get(w, "relevant word")
        ant = ANTONYMS.get(w, "opposite")
        random_word = random.choice([wd["word"] for wd in WORDS_OF_DAY if wd["word"] != w])
        gerund = w + "ing" if not w.endswith("e") else w[:-1] + "ing"
        for t in MIDDLE_TEMPLATES:
            q = t["question"].format(
                word=w, synonym=syn, antonym=ant, random_word=random_word,
                word_gerund=gerund, example=ex, example_translation=ex_trans,
                fake_trans1=fake1, fake_trans2=fake2
            )
            opts = [opt.format(
                word=w, synonym=syn, antonym=ant, random_word=random_word,
                word_gerund=gerund, example=ex, example_translation=ex_trans,
                fake_trans1=fake1, fake_trans2=fake2
            ) for opt in t["options"]]
            tasks.append({
                "question": q,
                "options": opts,
                "correct": t["correct"],
                "word": w
            })
    elif level == "pro":
        idiom = f"to {w} the boat" if w == "rock" else f"{w} the bullet" if w == "bite" else f"out of the {w}"
        fake_idiom1, fake_idiom2 = "fake idiom one", "another fake"
        complex_sentence = f"He finally decided to {w} the situation." if "the" not in w else f"She couldn't {w}."
        paraphrase = f"A different way of saying '{ex}'"
        for t in PRO_TEMPLATES:
            q = t["question"].format(
                word=w, idiom=idiom, fake_idiom1=fake_idiom1, fake_idiom2=fake_idiom2,
                complex_sentence=complex_sentence, example=ex, paraphrase=paraphrase,
                bad_paraphrase="Wrong paraphrase", wrong_meaning="Incorrect meaning",
                distractor1=fake1, distractor2=fake2
            )
            opts = [opt.format(
                word=w, idiom=idiom, fake_idiom1=fake_idiom1, fake_idiom2=fake_idiom2,
                complex_sentence=complex_sentence, example=ex, paraphrase=paraphrase,
                bad_paraphrase="Wrong paraphrase", wrong_meaning="Incorrect meaning",
                distractor1=fake1, distractor2=fake2
            ) for opt in t["options"]]
            tasks.append({
                "question": q,
                "options": opts,
                "correct": t["correct"],
                "word": w
            })
    random.seed()
    return tasks