IRREGULAR_VERBS = [
    {"v1": "be", "v2": "was/were", "v3": "been", "translation": "быть"},
    {"v1": "become", "v2": "became", "v3": "become", "translation": "становиться"},
    {"v1": "begin", "v2": "began", "v3": "begun", "translation": "начинать"},
    {"v1": "blow", "v2": "blew", "v3": "blown", "translation": "дуть"},
    {"v1": "break", "v2": "broke", "v3": "broken", "translation": "ломать"},
    {"v1": "bring", "v2": "brought", "v3": "brought", "translation": "приносить"},
    {"v1": "build", "v2": "built", "v3": "built", "translation": "строить"},
    {"v1": "buy", "v2": "bought", "v3": "bought", "translation": "покупать"},
    {"v1": "catch", "v2": "caught", "v3": "caught", "translation": "ловить"},
    {"v1": "choose", "v2": "chose", "v3": "chosen", "translation": "выбирать"},
    {"v1": "come", "v2": "came", "v3": "come", "translation": "приходить"},
    {"v1": "cost", "v2": "cost", "v3": "cost", "translation": "стоить"},
    {"v1": "cut", "v2": "cut", "v3": "cut", "translation": "резать"},
    {"v1": "do", "v2": "did", "v3": "done", "translation": "делать"},
    {"v1": "draw", "v2": "drew", "v3": "drawn", "translation": "рисовать"},
    {"v1": "drink", "v2": "drank", "v3": "drunk", "translation": "пить"},
    {"v1": "drive", "v2": "drove", "v3": "driven", "translation": "водить (машину)"},
    {"v1": "eat", "v2": "ate", "v3": "eaten", "translation": "есть (кушать)"},
    {"v1": "fall", "v2": "fell", "v3": "fallen", "translation": "падать"},
    {"v1": "feel", "v2": "felt", "v3": "felt", "translation": "чувствовать"},
    {"v1": "fight", "v2": "fought", "v3": "fought", "translation": "сражаться, драться"},
    {"v1": "find", "v2": "found", "v3": "found", "translation": "находить"},
    {"v1": "fly", "v2": "flew", "v3": "flown", "translation": "летать"},
    {"v1": "forget", "v2": "forgot", "v3": "forgotten", "translation": "забывать"},
    {"v1": "get", "v2": "got", "v3": "got/gotten", "translation": "получать, становиться"},
    {"v1": "give", "v2": "gave", "v3": "given", "translation": "давать"},
    {"v1": "go", "v2": "went", "v3": "gone", "translation": "идти, ехать"},
    {"v1": "grow", "v2": "grew", "v3": "grown", "translation": "расти, выращивать"},
    {"v1": "have", "v2": "had", "v3": "had", "translation": "иметь"},
    {"v1": "hear", "v2": "heard", "v3": "heard", "translation": "слышать"},
    {"v1": "hide", "v2": "hid", "v3": "hidden", "translation": "прятать"},
    {"v1": "hit", "v2": "hit", "v3": "hit", "translation": "ударять"},
    {"v1": "hold", "v2": "held", "v3": "held", "translation": "держать"},
    {"v1": "hurt", "v2": "hurt", "v3": "hurt", "translation": "причинять боль"},
    {"v1": "keep", "v2": "kept", "v3": "kept", "translation": "хранить, продолжать"},
    {"v1": "know", "v2": "knew", "v3": "known", "translation": "знать"},
    {"v1": "lay", "v2": "laid", "v3": "laid", "translation": "класть, накрывать"},
    {"v1": "lead", "v2": "led", "v3": "led", "translation": "вести, руководить"},
    {"v1": "learn", "v2": "learned/learnt", "v3": "learned/learnt", "translation": "учить(ся)"},
    {"v1": "leave", "v2": "left", "v3": "left", "translation": "покидать, оставлять"},
    {"v1": "lend", "v2": "lent", "v3": "lent", "translation": "давать взаймы"},
    {"v1": "let", "v2": "let", "v3": "let", "translation": "позволять"},
    {"v1": "lie", "v2": "lay", "v3": "lain", "translation": "лежать"},
    {"v1": "lose", "v2": "lost", "v3": "lost", "translation": "терять, проигрывать"},
    {"v1": "make", "v2": "made", "v3": "made", "translation": "делать, создавать"},
    {"v1": "mean", "v2": "meant", "v3": "meant", "translation": "значить, иметь в виду"},
    {"v1": "meet", "v2": "met", "v3": "met", "translation": "встречать"},
    {"v1": "pay", "v2": "paid", "v3": "paid", "translation": "платить"},
    {"v1": "put", "v2": "put", "v3": "put", "translation": "класть, ставить"},
    {"v1": "read", "v2": "read", "v3": "read", "translation": "читать"},
    {"v1": "ride", "v2": "rode", "v3": "ridden", "translation": "ехать верхом"},
    {"v1": "ring", "v2": "rang", "v3": "rung", "translation": "звонить, звенеть"},
    {"v1": "rise", "v2": "rose", "v3": "risen", "translation": "подниматься"},
    {"v1": "run", "v2": "ran", "v3": "run", "translation": "бежать"},
    {"v1": "say", "v2": "said", "v3": "said", "translation": "сказать"},
    {"v1": "see", "v2": "saw", "v3": "seen", "translation": "видеть"},
    {"v1": "sell", "v2": "sold", "v3": "sold", "translation": "продавать"},
    {"v1": "send", "v2": "sent", "v3": "sent", "translation": "посылать"},
    {"v1": "set", "v2": "set", "v3": "set", "translation": "устанавливать"},
    {"v1": "shake", "v2": "shook", "v3": "shaken", "translation": "трясти"},
    {"v1": "shine", "v2": "shone", "v3": "shone", "translation": "светить, сиять"},
    {"v1": "shoot", "v2": "shot", "v3": "shot", "translation": "стрелять"},
    {"v1": "show", "v2": "showed", "v3": "shown/showed", "translation": "показывать"},
    {"v1": "shut", "v2": "shut", "v3": "shut", "translation": "закрывать"},
    {"v1": "sing", "v2": "sang", "v3": "sung", "translation": "петь"},
    {"v1": "sink", "v2": "sank", "v3": "sunk", "translation": "тонуть"},
    {"v1": "sit", "v2": "sat", "v3": "sat", "translation": "сидеть"},
    {"v1": "sleep", "v2": "slept", "v3": "slept", "translation": "спать"},
    {"v1": "slide", "v2": "slid", "v3": "slid", "translation": "скользить"},
    {"v1": "speak", "v2": "spoke", "v3": "spoken", "translation": "говорить"},
    {"v1": "spend", "v2": "spent", "v3": "spent", "translation": "тратить"},
    {"v1": "stand", "v2": "stood", "v3": "stood", "translation": "стоять"},
    {"v1": "steal", "v2": "stole", "v3": "stolen", "translation": "красть"},
    {"v1": "strike", "v2": "struck", "v3": "struck/stricken", "translation": "бить, ударять"},
    {"v1": "swim", "v2": "swam", "v3": "swum", "translation": "плавать"},
    {"v1": "take", "v2": "took", "v3": "taken", "translation": "брать, взять"},
    {"v1": "teach", "v2": "taught", "v3": "taught", "translation": "учить, преподавать"},
    {"v1": "tear", "v2": "tore", "v3": "torn", "translation": "рвать"},
    {"v1": "tell", "v2": "told", "v3": "told", "translation": "рассказывать"},
    {"v1": "think", "v2": "thought", "v3": "thought", "translation": "думать"},
    {"v1": "throw", "v2": "threw", "v3": "thrown", "translation": "бросать"},
    {"v1": "understand", "v2": "understood", "v3": "understood", "translation": "понимать"},
    {"v1": "wake", "v2": "woke", "v3": "woken", "translation": "будить, просыпаться"},
    {"v1": "wear", "v2": "wore", "v3": "worn", "translation": "носить (одежду)"},
    {"v1": "win", "v2": "won", "v3": "won", "translation": "побеждать"},
    {"v1": "write", "v2": "wrote", "v3": "written", "translation": "писать"},
    # Дополнительные (расширенный список)
    {"v1": "arise", "v2": "arose", "v3": "arisen", "translation": "возникать"},
    {"v1": "awake", "v2": "awoke", "v3": "awoken", "translation": "просыпаться"},
    {"v1": "bear", "v2": "bore", "v3": "born/borne", "translation": "нести, рождать"},
    {"v1": "beat", "v2": "beat", "v3": "beaten/beat", "translation": "бить"},
    {"v1": "bend", "v2": "bent", "v3": "bent", "translation": "сгибать"},
    {"v1": "bet", "v2": "bet/betted", "v3": "bet/betted", "translation": "держать пари"},
    {"v1": "bite", "v2": "bit", "v3": "bitten", "translation": "кусать"},
    {"v1": "bleed", "v2": "bled", "v3": "bled", "translation": "кровоточить"},
    {"v1": "broadcast", "v2": "broadcast", "v3": "broadcast", "translation": "транслировать"},
    {"v1": "burn", "v2": "burned/burnt", "v3": "burned/burnt", "translation": "гореть, жечь"},
    {"v1": "burst", "v2": "burst", "v3": "burst", "translation": "взрываться"},
    {"v1": "cast", "v2": "cast", "v3": "cast", "translation": "бросать (актёра)"},
    {"v1": "cling", "v2": "clung", "v3": "clung", "translation": "цепляться"},
    {"v1": "creep", "v2": "crept", "v3": "crept", "translation": "ползти, красться"},
    {"v1": "deal", "v2": "dealt", "v3": "dealt", "translation": "иметь дело"},
    {"v1": "dig", "v2": "dug", "v3": "dug", "translation": "копать"},
    {"v1": "dive", "v2": "dove/dived", "v3": "dived", "translation": "нырять"},
    {"v1": "dream", "v2": "dreamed/dreamt", "v3": "dreamed/dreamt", "translation": "мечтать, сниться"},
    {"v1": "dwell", "v2": "dwelt/dwelled", "v3": "dwelt/dwelled", "translation": "обитать"},
    {"v1": "feed", "v2": "fed", "v3": "fed", "translation": "кормить"},
    {"v1": "flee", "v2": "fled", "v3": "fled", "translation": "убегать, спасаться"},
    {"v1": "fling", "v2": "flung", "v3": "flung", "translation": "швырять"},
    {"v1": "forbid", "v2": "forbade", "v3": "forbidden", "translation": "запрещать"},
    {"v1": "forecast", "v2": "forecast", "v3": "forecast", "translation": "прогнозировать"},
    {"v1": "freeze", "v2": "froze", "v3": "frozen", "translation": "замерзать"},
    {"v1": "grind", "v2": "ground", "v3": "ground", "translation": "молоть, шлифовать"},
    {"v1": "hang", "v2": "hung", "v3": "hung", "translation": "вешать"},
    {"v1": "kneel", "v2": "knelt/kneeled", "v3": "knelt/kneeled", "translation": "стоять на коленях"},
    {"v1": "knit", "v2": "knit/knitted", "v3": "knit/knitted", "translation": "вязать"},
    {"v1": "leap", "v2": "leaped/leapt", "v3": "leaped/leapt", "translation": "прыгать"},
    {"v1": "light", "v2": "lit/lighted", "v3": "lit/lighted", "translation": "зажигать"},
    {"v1": "mistake", "v2": "mistook", "v3": "mistaken", "translation": "ошибаться"},
    {"v1": "mow", "v2": "mowed", "v3": "mowed/mown", "translation": "косить (траву)"},
    {"v1": "quit", "v2": "quit/quitted", "v3": "quit/quitted", "translation": "покидать, бросать"},
    {"v1": "rid", "v2": "rid/ridded", "v3": "rid/ridded", "translation": "избавлять"},
    {"v1": "seek", "v2": "sought", "v3": "sought", "translation": "искать"},
    {"v1": "sow", "v2": "sowed", "v3": "sown/sowed", "translation": "сеять"},
    {"v1": "spell", "v2": "spelled/spelt", "v3": "spelled/spelt", "translation": "произносить по буквам"},
    {"v1": "spill", "v2": "spilled/spilt", "v3": "spilled/spilt", "translation": "проливать"},
    {"v1": "spin", "v2": "spun", "v3": "spun", "translation": "крутить"},
    {"v1": "spit", "v2": "spat/spit", "v3": "spat/spit", "translation": "плевать"},
    {"v1": "split", "v2": "split", "v3": "split", "translation": "разделять, раскалывать"},
    {"v1": "spoil", "v2": "spoiled/spoilt", "v3": "spoiled/spoilt", "translation": "портить"},
    {"v1": "spread", "v2": "spread", "v3": "spread", "translation": "распространять"},
    {"v1": "spring", "v2": "sprang", "v3": "sprung", "translation": "прыгать, бить ключом"},
    {"v1": "stick", "v2": "stuck", "v3": "stuck", "translation": "приклеивать, застревать"},
    {"v1": "sting", "v2": "stung", "v3": "stung", "translation": "жалить"},
    {"v1": "stink", "v2": "stank/stunk", "v3": "stunk", "translation": "вонять"},
    {"v1": "stride", "v2": "strode", "v3": "stridden", "translation": "шагать"},
    {"v1": "swear", "v2": "swore", "v3": "sworn", "translation": "клясться"},
    {"v1": "sweat", "v2": "sweated/sweat", "v3": "sweated/sweat", "translation": "потеть"},
    {"v1": "sweep", "v2": "swept", "v3": "swept", "translation": "подметать"},
    {"v1": "swell", "v2": "swelled", "v3": "swollen/swelled", "translation": "опухать"},
    {"v1": "swing", "v2": "swung", "v3": "swung", "translation": "качаться"},
    {"v1": "thrust", "v2": "thrust", "v3": "thrust", "translation": "толкать, пронзать"},
    {"v1": "tread", "v2": "trod", "v3": "trodden/trod", "translation": "ступать"},
    {"v1": "weep", "v2": "wept", "v3": "wept", "translation": "плакать"},
    {"v1": "wind", "v2": "wound", "v3": "wound", "translation": "заводить (часы), виться"},
    {"v1": "withdraw", "v2": "withdrew", "v3": "withdrawn", "translation": "отзывать, снимать (деньги)"},
    {"v1": "withhold", "v2": "withheld", "v3": "withheld", "translation": "удерживать"},
    {"v1": "withstand", "v2": "withstood", "v3": "withstood", "translation": "выстоять, выдерживать"},
    {"v1": "wring", "v2": "wrung", "v3": "wrung", "translation": "выжимать, скручивать"},
]